// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXffbNxCxmhztZGvc9plHKw92bjbOGgGI',
    appId: '1:965320825406:android:fbdf4b32a0f5cf1a1ecf6f',
    messagingSenderId: '965320825406',
    projectId: 'emiraride-4ee4d',
    storageBucket: 'emiraride-4ee4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW7IuhHma-RyQqeUqzkOgENONIY4AAaf8',
    appId: '1:965320825406:ios:218fbc8a43ea63bf1ecf6f',
    messagingSenderId: '965320825406',
    projectId: 'emiraride-4ee4d',
    storageBucket: 'emiraride-4ee4d.firebasestorage.app',
    androidClientId: '965320825406-8hb5b1q2jl19lq8l64bt8253kb2ugt4f.apps.googleusercontent.com',
    iosClientId: '965320825406-62fda9g9vh4crqp1ls15ufg47is7tkgs.apps.googleusercontent.com',
    iosBundleId: 'com.inferloom.emirarider',
  );

}